apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew-plugin-template-test
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/DexterYan/krew-plugin-template-test/releases/download/v0.1.0/krew-plugin-template-test_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-template-test"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-template-test"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/DexterYan/krew-plugin-template-test/releases/download/v0.1.0/krew-plugin-template-test_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./krew-plugin-template-test"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-template-test"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/DexterYan/krew-plugin-template-test/releases/download/v0.1.0/krew-plugin-template-test_windows_amd64.zip
    sha256: ""
    files:
    - from: "/krew-plugin-template-test.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "krew-plugin-template-test.exe"
  shortDescription: A new plugin
  homepage: https://github.com/DexterYan/krew-plugin-template-test
  caveats: |
    Usage:
      $ kubectl krew-plugin-template-test

    For additional options:
      $ kubectl krew-plugin-template-test --help
      or https://github.com/DexterYan/krew-plugin-template-test/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
